src/DevSlkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using System.Web;
using AutoMapper;
using DevSkill.Inventory.Application.Services;
using DevSkill.Inventory.Web.Areas.Admin.Models;
using DevSkill.Inventory.Domain.Entities;
using DevSkill.Inventory.Infrastructure;
using Microsoft.Identity.Client;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace DevSkill.Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
	public class StockController : Controller
	{
		private readonly IStockManagementService _stockManagementService;
		private readonly IWarehouseManagementService _warehouseManagementService;
		private readonly IProductManagementService _productManagementService;
		private readonly ILogger<StockController> _logger;
		private readonly IMapper _mapper;
		public StockController(ILogger<StockController> logger,
			IMapper mapper, IStockManagementService stockManagementService,
			IWarehouseManagementService warehouseManagementService,
			IProductManagementService productManagementService)
		{
			_stockManagementService = stockManagementService;
			_warehouseManagementService = warehouseManagementService;
			_productManagementService = productManagementService;
			_logger = logger;
			_mapper = mapper;
		}

		[Authorize(Roles = "Member,Admin,Support")]
		public IActionResult Index()
		{
			var model = new StockListModel();
			model.SetWarehouseValues(_warehouseManagementService.GetWarehouses());
			model.SetProductValues(_productManagementService.GetProducts());
			return View(model);
		}

		[HttpPost, Authorize(Roles = "Member,Admin,Support")]
		public async Task<JsonResult> GetStockJsonData([FromBody] StockListModel model)
		{
			var result = await _stockManagementService.
				GetStocksSP(model.PageIndex, model.PageSize, model.SearchItem,
				model.FormatSortExpression("Id","Product","Warehouse","Quantity","Reason"));
			var stockJsonData = new
			{
				recordsTotal = result.total,
				recordsFiltered = result.totalDisplay,
				data = (from record in result.data
						select new string[]
						{
								HttpUtility.HtmlEncode(record.Date),
								HttpUtility.HtmlEncode(record.Product),
								HttpUtility.HtmlEncode(record.Warehouse),
								HttpUtility.HtmlEncode(record.Quantity),
								HttpUtility.HtmlEncode(record.PurchasePrice),
								HttpUtility.HtmlEncode(record.SellingPrice),
                                HttpUtility.HtmlEncode(record.Reason),
								HttpUtility.HtmlEncode(record.Note),
								record.Id.ToString()
						}
					).ToArray()
			};
			return Json(stockJsonData);
        }

        [Authorize(Roles = "Admin,Support")]
        public IActionResult Create()
		{
			var model = new StockCreateModel();
			model.SetDateOnlyValues();
			model.SetProductValues(_productManagementService.GetProducts());
			model.SetWarehouseValues(_warehouseManagementService.GetWarehouses());
			return View(model);
		}
		[HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin,Support")]
		public IActionResult Create(StockCreateModel model)
		{
            if (ModelState.IsValid)
            {
                var stock = _mapper.Map<Stock>(model);
				stock.Id = Guid.NewGuid();
				stock.SellingPrice = model.ProfitCalculation(model.Profit, model.PurchasePrice);
				stock.Reason = "New item";
				stock.WantToProfit = model.Profit;
				stock.Product = _productManagementService.GetProduct(model.ProductId);
				stock.Warehouse = _warehouseManagementService.GetWarehouse(model.WarehouseId);

				try
				{
					_stockManagementService.CreateStock(stock);

					TempData.Put("ResponseMessage", new ResponseModel
					{
						Message = "Stock added successfuly",
						Type = ResponseTypes.Success
					});

					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					TempData.Put("ResponseMessage", new ResponseModel
					{
						Message = "Stock added failed",
						Type = ResponseTypes.Danger
					});

					_logger.LogError(ex, "Stock added failed");
				}
			}

			model.SetDateOnlyValues();
			model.SetProductValues(_productManagementService.GetProducts());
			model.SetWarehouseValues(_warehouseManagementService.GetWarehouses());
			return View(model);
		}

		[Authorize(Roles = "Admin,Support")]
		public async Task<IActionResult> Update(Guid id)
		{
			var stock = await _stockManagementService.GetStockInformationAsync(id);
            var model = _mapper.Map<StockUpdateModel>(stock);
            var product = await _productManagementService.GetProductInformationAsync(model.ProductId);
			var warehouse = await _warehouseManagementService.GetWarehouseInformationAsync(model.WarehouseId);
            model.ProductName = product.Name;
			model.WarehouseName = warehouse.Name;
			model.SellingPrice = stock.SellingPrice;
			model.Profit = stock.WantToProfit;
			model.SetDateOnlyValues();
            return PartialView("_StockUpdateModalPartial",model);
		}


		[HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin,Support")]
		public async Task<IActionResult> Update(StockUpdateModel model)
		{
			if (ModelState.IsValid)
			{
                var stock = await _stockManagementService.GetStockInformationAsync(model.Id);
                stock = _mapper.Map(model, stock);
				stock.Quantity = stock.Quantity + model.AddStock;
				if(stock.Quantity == 0)
				{
					stock.PurchasePrice = 0;
					stock.SellingPrice = 0;
				}
				else
				{
                    stock.PurchasePrice = model.CurrentPriceCalculation();
                    stock.SellingPrice = model.ProfitCalculation();
                }             
				
				_stockManagementService.UpdateStock(stock);
                TempData.Put("ResponseMessage", new ResponseModel
                {
                    Message = "Stock added successfuly",
                    Type = ResponseTypes.Success
                });
                return RedirectToAction("Index");
			}
			return PartialView("_StockUpdateModalPartial", model);
		}


		[HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin,Support")]
		public IActionResult Delete(Guid Id)
		{
			try
			{
				_stockManagementService.DeleteStock(Id);
				TempData.Put("ResponseMessage", new ResponseModel
				{
					Message = "Stock deleted successfull.",
					Type = ResponseTypes.Success
				});
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				TempData.Put("ResponseMessage", new ResponseModel
				{
					Message = "Stock delete failed!",
					Type = ResponseTypes.Danger
				});
				_logger.LogError(ex, "Stock delete failed!");
			}
			return View();
		}
	}
}

src/DevSlkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/Stock/Create.cshtml
@model StockCreateModel
@{
    ViewData["Title"] = "Create";
}

@section Scripts {
    <script>
    </script>

}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h5>Stock New Item</h5>
            </div>
        </div>
        <!-- /.container-fluid -->
        <h1 class="border-bottom border-2 border-primary"></h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card card-primary">
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form asp-antiforgery="true" asp-area="Admin" asp-controller="Stock" asp-action="Create" method="post" enctype="multipart/form-data">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label asp-for="Date">Date:&nbsp;</label>
                                        <input type="date" asp-for="Date" class="form-control-inline" />
                                        <span asp-validation-for="Date" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label asp-for="WarehouseId">Branch:&nbsp;</label>
                                        <select asp-for="WarehouseId" asp-items="Model.Warehouses" class="form-control-inline"></select>
                                        <span asp-validation-for="WarehouseId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <table class="table table-bordered">
                                        <thead style="background: #17A2B8">
                                            <tr class="text-center">
                                                <th class="col-4">Item</th>
                                                <th>Quantity</th>
                                                <th>Cost Per Unit</th>
                                                <th>Profit (%)</th>
                                                <th>Note</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th>
                                                    <select asp-for="ProductId" asp-items="Model.Products" class="form-control"></select>
                                                    <span asp-validation-for="ProductId" class="text-danger"></span>
                                                </th>
                                                <th>
                                                    <input type="text" asp-for="Quantity" class="form-control" placeholder="Quantity" />
                                                    <span asp-validation-for="Quantity" class="text-danger"></span>
                                                </th>
                                                <th>
                                                    <input type="text" asp-for="PurchasePrice" class="form-control" placeholder="Unit price"/>
                                                    <span asp-validation-for="PurchasePrice" class="text-danger"></span>
                                                </th>
                                                <th>
                                                    <input type="text" asp-for="Profit" class="form-control" placeholder="Example: 10"/>
                                                    <span asp-validation-for="Profit" class="text-danger"></span>
                                                </th>
                                                <th>
                                                    <input type="text" asp-for="Note" class="form-control" placeholder="Note"/>
                                                    <span asp-validation-for="Note" class="text-danger"></span>
                                                </th>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>                               
                            </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-success btn-sm">
                                <i class="fas fa-save"></i>
                                Save
                            </button>
                            <button type="button" class="btn btn-danger btn-sm">
                                <i _ngcontent-myr-c237="" class="fas fa-times-circle"></i>
                                Cancel
                            </button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->

src/DevSlkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/Stock/Index.cshtml
@model StockListModel
@section Styles
{
	<link rel="stylesheet" href="~/AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="~/AdminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
	<link rel="stylesheet" href="~/AdminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

@section Scripts
{
	<script src="~/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
	<script src="~/AdminLTE/plugins/jszip/jszip.min.js"></script>
	<script src="~/AdminLTE/plugins/pdfmake/pdfmake.min.js"></script>
	<script src="~/AdminLTE/plugins/pdfmake/vfs_fonts.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

	<script>
		$(function () {
			$("#stocks").DataTable({
				processing: true,
				serverSide: true,
				responsive: true,
				searching: false,
				lengthChange: false,
				autoWidth: true,
				lengthMenu: [
					[10, 25, 50, -1],
					[10, 25, 50, 'All']
				],
				ajax: {
					url: "/Admin/Stock/GetStockJsonData",
					type: "POST",
					contentType: "application/json",
					dataType: "json",
					data: function (d) {
						d.SearchItem = {
						};
						return JSON.stringify(d);
					},
				},
				columnDefs: [
					{
						className: "text-center",
						targets: "_all"
					},
					{
						orderable: true,
						targets: 0,
						render: function (data) {
							const date = new Date(data);
							const day = date.getDate().toString().padStart(2, '0');
							const month = date.toLocaleString('default', { month: 'short' });
							const year = date.getFullYear();
							return `${day}-${month}-${year}`;
						}
					},
					{
						orderable: false,
						targets: 8,
						render: function (data, type, row) {
							console.log(type);
							return `<button type="submit" class="btn btn-success btn-sm show-bs-EditModal" style="width:28px" data-id='${data}' value='${data}'>
																<i class="fas fa-plus"></i> 
																			</button>							
															<button type="submit" class="btn btn-danger btn-sm show-bs-modal" style="width:28px" data-id='${data}' value='${data}'>
																				<i class="fas fa-trash">
																				</i>
																			</button>`;
						}
					}
				],
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#stocks_wrapper .col-sm-12:eq(0)');

			$('#stocks').on('click', '.show-bs-modal', function (event) {
				let id = $(this).data("id");
				let modal = $("#modal-default");
				modal.find('.modal-body p').text('Are you sure you want to delete this record?');
				$("#deleteId").val(id);
				$("#deleteForm").attr("action", "/admin/stock/delete");
				modal.modal('show');
			});

			$("#deleteButton").click(function () {
				$("#deleteForm").submit();
			});
			$("#searchButton").click(function () {
				$("#stocks").DataTable().ajax.reload(null, false);
			});
		});
	</script>
	<script>
		$(document).ready(function () {
			$('#stocks').on('click', '.show-bs-EditModal', function () {
				const id = $(this).data('id');
				$.ajax({
					url: `/Admin/Stock/Update/${id}`,
					type: 'GET',
					success: function (response) {
						$('#UpdateStockModalContainer').html(response);
						$('#UpdateStockModal').modal('show');
					},
					error: function () {
						alert('Failed to load data for editing');
					}
				});
			});
		});
	</script>


}

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="card">
			<div class="card-body">
				<div class="row mb-1">
					<div class="col-sm-10">
						<h5>Stock Adjustments</h5>
					</div>
					<div class="col-sm-2">
						<button type="button" class="btn btn-info btn-sm" style="height:30px" onclick="window.location.href='/admin/stock/create/'">
							<p>
								<i _ngcontent-yib-c224="" class="fas fa-plus"></i>
								&nbsp;Stock New Item
							</p>
						</button>
					</div>
				</div>
				<h1 class="border-bottom border-1 border-info"></h1>
				<div id="UpdateStockModalContainer"></div>
				<partial name="_ResponsePartial" />
				<partial name="_ModalPartial" />
				<table id="stocks" class="table table-bordered table-striped">
					<thead style="background: #17A2B8">
						<tr>
							<th style="color:white">Date</th>
							<th style="color:white">Product</th>
							<th style="color:white">Warehouse</th>
							<th style="color:white">Quantity</th>
							<th style="color:white">Cost per unit</th>
							<th style="color:white">Sell Price</th>
							<th style="color:white">Reason</th>
							<th style="color:white">Note</th>
							<th class="col-1" style="color:white">Action</th>
						</tr>
					</thead>
				</table>
			</div>
			<!-- /.card-body -->
		</div>
		<!-- /.card -->
	</div>
	<!-- /.container-fluid -->
</section>
<!-- /.content -->