src/DevSlkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Controllers/MemberController.cs
using DevSkill.Inventory.Infrastructure;
using DevSkill.Inventory.Infrastructure.Identity;
using DevSkill.Inventory.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DevSkill.Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class MemberController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public MemberController(RoleManager<ApplicationRole> roleManager, 
            UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

		[Authorize(Roles = "Admin")]
		public IActionResult Index()
        {
            return View();
        }

		[HttpPost, Authorize(Roles = "Admin")]
		public async Task<IActionResult> GetUserRolesJsonData()
		{
			var users = await _userManager.Users.ToListAsync();
			var userRolesData = new List<UserRoleModel>();

			foreach (var user in users)
			{
				var roles = await _userManager.GetRolesAsync(user);
                userRolesData.Add(new UserRoleModel
                {
                    UserName = user.UserName,
                    Role = string.Join(", ", roles)
                });
			}

			return Json(userRolesData);
		}


		[Authorize(Roles = "Admin")]
        public IActionResult CreateRole()
        {
            var model = new RoleCreateModel();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateRole(RoleCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _roleManager.CreateAsync(new ApplicationRole
                    {
                        Id = Guid.NewGuid(),
                        NormalizedName = model.RoleName.ToUpper(),
                        Name = model.RoleName,
                        ConcurrencyStamp = DateTime.UtcNow.Ticks.ToString()
                    });
                    TempData.Put("ResponseMessage", new ResponseModel
                    {
                        Message = "Role create successfull.",
                        Type = ResponseTypes.Success
                    });
                    return RedirectToAction("Index");
                }
                catch
                {
                    TempData.Put("ResponseMessage", new ResponseModel
                    {
                        Message = "Role create failed.",
                        Type = ResponseTypes.Danger
                    });
                }
                
            }

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ChangeRole()
        {
            var model = new RoleChangeModel();
            LoadValues(model);
            return View(model);
        }


        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin")]
        public async Task<IActionResult> ChangeRole(RoleChangeModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(model.UserId.ToString());
                    var roles = await _userManager.GetRolesAsync(user);
                    await _userManager.RemoveFromRolesAsync(user, roles);
                    var newRole = await _roleManager.FindByIdAsync(model.RoleId.ToString());
                    await _userManager.AddToRoleAsync(user, newRole.Name);
                    TempData.Put("ResponseMessage", new ResponseModel
                    {
                        Message = "Role change successfull.",
                        Type = ResponseTypes.Success
                    });
                    return RedirectToAction("Index");
                }
                catch
                {
                    TempData.Put("ResponseMessage", new ResponseModel
                    {
                        Message = "Role change failed.",
                        Type = ResponseTypes.Danger
                    });
                }
                
            }
            LoadValues(model);
            return View(model);
        }

        private void LoadValues(RoleChangeModel model)
        {
            var users = from c in _userManager.Users.ToList() select c;
            var roles = from c in _roleManager.Roles.ToList() select c;

            model.UserId = users.First().Id;
            model.RoleId = roles.First().Id;

            model.Users = new SelectList(users, "Id", "UserName");
            model.Roles = new SelectList(roles, "Id", "Name");
        }
    }
}

src/DevSlkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/Member/ChangeRole.cshtml
@model RoleChangeModel
@{
    ViewData["Title"] = "Role Change";
    <link rel="stylesheet" href="~/css/CreateRole.css" />
}

<div class="container bg-white d-flex justify-content-center" style="width: 30%; border-radius: 12px; margin-top: 40px;margin-bottom:300px">
    <div class="card-body">
        <section>
            <p class="text-center" style="font-size:20px; font:bold">Change Role</p>
            <form asp-antiforgery="true" asp-area="Admin" asp-controller="Member" asp-action="ChangeRole" method="post">
                <partial name="_ResponsePartial" />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="UserId">User Name</label>
                        <select asp-for="UserId" asp-items="Model.Users" class="form-control"></select>
                        <span asp-validation-for="UserId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RoleId">Role Name</label>
                        <select asp-for="RoleId" asp-items="Model.Roles" class="form-control"></select>
                        <span asp-validation-for="RoleId" class="text-danger"></span>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-info" style="width:100%">Submit</button>
                </div>
            </form>
        </section>
    </div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/DevSlkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/Member/CreateRole.cshtml
@model RoleCreateModel

@{
    ViewData["Title"] = "Create Role";
    <link rel="stylesheet" href="~/css/CreateRole.css" />

}

<div class="container bg-white d-flex justify-content-center" style="width: 30%; border-radius: 12px; margin-top: 40px;margin-bottom:300px">
    <div class="card-body">
        <section>
        <p class="text-center" style="font-size:20px; font:bold">Create Role</p>        
            <form asp-antiforgery="true" asp-area="Admin" asp-controller="Member" asp-action="CreateRole" method="post">
                <partial name="_ResponsePartial" />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="RoleName"></label>
                        <input type="text" asp-for="RoleName" class="form-control" />
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-info" style="width:100%">Submit</button>
                </div>
            </form>
        </section>
    </div>
 
@section Scripts {
        <partial name="_ValidationScriptsPartial" />
}

src/DevSlkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/Member/Index.cshtml
@{
	ViewData["Title"] = "Index";
}

@section Styles
{
	<link rel="stylesheet" href="~/AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="~/AdminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
	<link rel="stylesheet" href="~/AdminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

@section Scripts
{
	<script src="~/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
	<script src="~/AdminLTE/plugins/jszip/jszip.min.js"></script>
	<script src="~/AdminLTE/plugins/pdfmake/pdfmake.min.js"></script>
	<script src="~/AdminLTE/plugins/pdfmake/vfs_fonts.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js"></script>
	<script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>


	<script>
		$(function () {
			$("#members").DataTable({
				processing: true,
				serverSide: false,
				responsive: true,
				searching: false,
				lengthChange: false,
				autoWidth: true,
				lengthMenu: [
					[10, 25, 50, -1],
					[10, 25, 50, 'All']
				],
				ajax: {
					url: "/Admin/Member/GetUserRolesJsonData",
					type: "POST",
					contentType: "application/json",
					dataType: "json",
					dataSrc: ""
				},
				columns: [
					{ data: "userName", title: "User Name" },
					{ data: "role", title: "Role" }
				]
			});
		});
	</script>
}

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
				<div class="card col-12">
					<!-- /.card-header -->
					<div class="card-body">
						<div class="row mb-1">
							<div class="col-12">
								<h5>User Roles</h5>
							</div>
						</div>
						<h1 class="border-bottom border-1 border-info"></h1>
						<partial name="_ResponsePartial" />
						<table id="members" class="table table-bordered table-striped">
							<thead style="background: #17A2B8;color:white">
								<tr>
									<th>User Name</th>
									<th>Role</th>
								</tr>
							</thead>
						</table>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
		</div>
		<!-- /.row -->
	</div>
	<!-- /.container-fluid -->
</section>
<!-- /.content -->